spring:
  profiles:
    include: [center]
  ####### database Config #######
  datasource:
    druid:
      connection-init-sqls: set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://123.59.196.96:3306/dblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ls@123456
  ####### Redis Config #######
  redis:
    database: 5
    # Redis服务器地址
    #host: 123.59.196.96
    # Redis服务器连接端口
    #port: 6379
    # Redis服务器连接密码（默认为空）
    password: ls@123456
    sentinel:
      # 主节点的别名
      master: mymaster
      # sentinel服务的ip和端口
      nodes: 123.59.196.96:26379,118.24.120.220:26379,47.111.95.247:26379
  ####### redis缓存服务配置 #######
  session:
    store-type: redis

  ####### 自定义配置 #######
  taobao:
    url: https://eco.taobao.com/router/rest
    appkey: 28485666
    secret: feac79d58095283addca7ab933500b89
  ####### 自定义配置 #######
