spring:
  profiles:
    include: [center]
  ####### database Config #######
  datasource:
    druid:
      connection-init-sqls: set names utf8mb4
      driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.24.120.220:3306/dblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ls@123456
  ####### Redis Config #######
  redis:
    #database: 5
    # Redis服务器地址
    #host: 123.59.196.96
    # Redis服务器连接端口
    #port: 6379
    # Redis服务器连接密码（默认为空）
    password: ls@123456
    sentinel:
      # 主节点的别名
      master: mymaster
      # sentinel服务的ip和端口,47.111.95.247:26379
      nodes: 123.59.196.96:26379,118.24.120.220:26379
    lettuce:
      pool:
      # 连接池最大连接数(使用负值表示没有限制) 默认为8
      max-active: 8
      # 连接池中的最大空闲连接 默认为8
      max-idle: 8
      # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
      max-wait: -1ms
      # 连接池中的最小空闲连接 默认为 0
      min-idle: 0
  ####### redis缓存服务配置 #######
  session:
    store-type: redis

  ####### 自定义配置 #######
  taobao:
    url: https://eco.taobao.com/router/rest
    appkey: 28485666
    secret: feac79d58095283addca7ab933500b89
  ####### 自定义配置 #######
